#!/usr/bin/env bash
# Package each skill source directory into a distributable .skill bundle, and
# emit the paste-channel artifact for hosts that cannot install a skill at all.
#
# A .skill file is a zip whose single top-level directory is the skill name,
# containing SKILL.md at its root. The source directories in this repo are
# authoritative; the .skill files and paper-session-paste.md are build
# artifacts (committed so people can install without cloning).
#
# Usage: ./build.sh [skill-name ...]      # default: all skills
#        ./build.sh --paste-body          # write the paste body to stdout, touch nothing
#        ./build.sh --check-fonts         # run the font guard alone, build nothing
#        ./build.sh --check-couplings     # run the cross-skill gate alone, build nothing

set -euo pipefail
cd "$(dirname "$0")"

FONT_DIR=paper-session/assets/fonts
PASTE=paper-session-paste.md
# Reading order, and the order the artifact concatenates them in: procedure
# first, then how to word a page, then which patterns exist.
PASTE_SOURCES=(
  paper-session/SKILL.md
  paper-session/references/prompt-craft.md
  paper-session/references/page-patterns.md
)

require_paste_sources() {
  for src in "${PASTE_SOURCES[@]}"; do
    [[ -f "$src" ]] || { echo "error: $src not found — the paste artifact needs all three sources" >&2; exit 1; }
  done
}

# The paste artifact's body: the three documents byte for byte, with exactly one
# deletion. This function is the only place that transformation exists — CI
# calls it through --paste-body rather than holding a second copy, because a
# duplicated mechanism is the drift this artifact is built to rule out.
paste_body() {
  require_paste_sources

  # SKILL.md's YAML frontmatter is install metadata for a runtime the paste
  # channel does not have, and it would sit above the instruction line as the
  # first thing the host reads — leading with "Generates a printable PDF
  # worksheet (reportlab)" on a surface that can produce no PDF. Drop the block
  # and the blank line after it; nothing else is touched, here or in the other
  # two files.
  awk 'NR==1 && $0=="---" { infm=1; next }
       infm && $0=="---"  { infm=0; gap=1; next }
       gap  && $0==""     { gap=0;  next }
       !infm              { gap=0; print }' "${PASTE_SOURCES[0]}"
  cat "${PASTE_SOURCES[1]}" "${PASTE_SOURCES[2]}"
}

write_paste() {
  require_paste_sources

  # The last line of this preamble is the sentinel the CI check keys on to find
  # where the generated body starts. Renaming it is a breaking change to that
  # check, which is the point: the failure is legible instead of silent.
  cat > "$PASTE" <<'PREAMBLE'
<!-- paper-session paste channel — generated by build.sh from repository source; do not edit -->

Paste this whole file into the chat. Then say what you are working on, and add this sentence: "I can't print, and you can't make a PDF here, so dictate the setup card for me to copy by hand — there is nothing to annotate."

This is the `paper-session` skill for chat products that cannot install skills. It is three documents from https://github.com/welovejeff/paper-session#install, in reading order: `SKILL.md`, then `references/prompt-craft.md`, then `references/page-patterns.md`. They are copied byte for byte with exactly one deletion: `SKILL.md`'s YAML frontmatter block, which is install metadata addressed to a runtime that is not here.

Two source documents are deliberately absent: `references/design.md`, a typographic spec for a PDF that cannot be produced here, and `references/evidence.md`, the sourcing layer. The text below still points at both, and at `scripts/verify_layout.py` and a PDF skill path. Those pointers are dead here and are not instructions to you: the card path produces no PDF and has no verify gate, and every rule that governs a card is stated in full below. Follow the rules; ignore the file paths.

The return half of the loop is a second paste: `scan-back/SKILL.md`, one file, into the same chat when the photographed pages come back.

<!-- source begins; everything below this line is generated from the three files above and is checked byte for byte in CI -->
PREAMBLE
  # Appended, not captured into a variable and echoed: command substitution
  # strips trailing newlines, and byte-faithfulness is the whole argument for
  # generating this file instead of writing one.
  preamble_bytes=$(wc -c < "$PASTE")
  paste_body >> "$PASTE"
  total_bytes=$(wc -c < "$PASTE")
  # An empty body means the awk filter swallowed the file rather than the
  # frontmatter — a silent, total failure that would otherwise ship.
  if [[ "$total_bytes" -le "$preamble_bytes" ]]; then
    echo "error: the paste body came out empty" >&2
    exit 1
  fi

  echo "built $PASTE — ${#PASTE_SOURCES[@]} documents, $total_bytes bytes"
}

# The three Sans faces once shipped as three copies of one variable font, all
# reporting usWeightClass 400, so SemiBold and Bold rendered as Regular and no
# gate noticed for the life of the project. design.md maps three voices onto
# eight registered faces; a face that does not carry the weight its name
# promises prints a voice at the wrong weight, silently. These read the source
# files, not a bundle, and run before anything is zipped, so a bad font never
# reaches an artifact.
check_fonts() {
  python3 - "$FONT_DIR" <<'PY'
import struct, sys
from pathlib import Path

# Every face design.md registers, with the usWeightClass its register implies.
EXPECTED = {
    "IBMPlexSans-Regular.ttf":   400,
    "IBMPlexSans-SemiBold.ttf":  600,
    "IBMPlexSans-Bold.ttf":      700,
    "IBMPlexSerif-Regular.ttf":  400,
    "IBMPlexSerif-Italic.ttf":   400,
    "IBMPlexSerif-SemiBold.ttf": 600,
    "IBMPlexMono-Regular.ttf":   400,
    "IBMPlexMono-Medium.ttf":    500,
}
SANS = ("IBMPlexSans-Regular.ttf", "IBMPlexSans-SemiBold.ttf", "IBMPlexSans-Bold.ttf")

def directory(b):
    """The TrueType table directory: tag -> (checksum, offset, length)."""
    count, = struct.unpack(">H", b[4:6])
    return {
        tag.decode("latin-1"): (cks, off, ln)
        for tag, cks, off, ln in (
            struct.unpack(">4sLLL", b[12 + 16 * i:28 + 16 * i]) for i in range(count)
        )
    }

def us_weight_class(b, tables):
    _, off, _ = tables["OS/2"]
    return struct.unpack(">H", b[off + 4:off + 6])[0]

def postscript_name(b, tables):
    _, off, _ = tables["name"]
    _, count, strings = struct.unpack(">HHH", b[off:off + 6])
    fallback = None
    for i in range(count):
        rec = off + 6 + 12 * i
        pid, _, _, nid, length, at = struct.unpack(">6H", b[rec:rec + 12])
        if nid != 6:
            continue
        raw = b[off + strings + at:off + strings + at + length]
        try:
            text = raw.decode("utf-16-be") if pid == 3 else raw.decode("latin-1")
        except UnicodeDecodeError:
            continue
        if pid == 3:
            return text
        fallback = fallback or text
    return fallback

fonts = Path(sys.argv[1])
errors, weights, names, outlines = [], {}, {}, {}

for face, want in EXPECTED.items():
    path = fonts / face
    if not path.is_file():
        errors.append(f"{face} is missing from {fonts}/")
        continue
    data = path.read_bytes()
    tables = directory(data)

    if "fvar" in tables:
        errors.append(f"{face} is a variable font (it carries fvar); reportlab renders it at "
                      "the default instance, not at the weight the filename promises")
    missing = [t for t in ("OS/2", "name", "glyf") if t not in tables]
    if missing:
        errors.append(f"{face} has no {', '.join(missing)} table")
        continue

    weights[face] = us_weight_class(data, tables)
    names[face] = postscript_name(data, tables)
    outlines[face] = tables["glyf"][0]
    if weights[face] != want:
        errors.append(f"{face} reports usWeightClass {weights[face]}, not the {want} its register implies")

# reportlab keys on the PostScript name, so two faces sharing one are one face.
shared = {}
for face, name in names.items():
    shared.setdefault(name, []).append(face)
for name, faces in sorted(shared.items()):
    if len(faces) > 1:
        errors.append(f"PostScript name '{name}' is shared by {', '.join(sorted(faces))}")

sans_weights = [weights[f] for f in SANS if f in weights]
if len(set(sans_weights)) != len(sans_weights):
    errors.append(f"the three Sans faces do not carry distinct usWeightClass values: {sans_weights}")

# The one assertion that catches the original defect on its own: three files
# correctly named and correctly reweighted but never re-outlined pass every
# check above and still print flat.
sans_outlines = [outlines[f] for f in SANS if f in outlines]
if len(set(sans_outlines)) != len(sans_outlines):
    errors.append(f"the three Sans faces share their glyf outlines (checksums {sans_outlines})")

for message in errors:
    print(f"error: {message}", file=sys.stderr)
sys.exit(1 if errors else 0)
PY
}

# The pen protocol is specified twice with no shared file — design.md §9 prints
# the ink key, scan-back Step 1 reads it back — so a change made on one side and
# not the other prints a key the return trip does not honour. Two clauses of it
# are pinned here by their exact words: the format scoping that narrows a
# handwritten legend to its own page, and the scribe carve-out that exempts a
# scribe from that narrowing. Each literal is asserted present in both
# documents, four assertions in all, naming the string and the file it fell out
# of.
#
# This is a presence gate and nothing more. It catches the failure this repo has
# already had once — one side reworded, the other left alone — and it cannot
# catch a rule that keeps the phrase while its meaning drifts, or two clauses
# that contradict each other in the words around the literal. Both sides passing
# is not evidence the pair agrees; reviewing the pair by hand is still the job.
COUPLED_DOCS=(scan-back/SKILL.md paper-session/references/design.md)
COUPLED_LITERALS=("a group format" "a scribe speaks for the author")

check_couplings() {
  broken=0
  for literal in "${COUPLED_LITERALS[@]}"; do
    for doc in "${COUPLED_DOCS[@]}"; do
      if [[ ! -f "$doc" ]]; then
        echo "error: $doc not found — the pen protocol has no second side to check" >&2
        broken=1
      elif ! grep -qF "$literal" "$doc"; then
        echo "error: \"$literal\" is missing from $doc — the pen protocol is specified in both ${COUPLED_DOCS[0]} and ${COUPLED_DOCS[1]}, and a change to one has to be made in the other" >&2
        broken=1
      fi
    done
  done
  [[ "$broken" -eq 0 ]] || exit 1
}

case "${1:-}" in
  --paste-body)      paste_body;      exit 0 ;;
  --check-fonts)     check_fonts;     exit 0 ;;
  --check-couplings) check_couplings; exit 0 ;;
esac

SKILLS=("${@:-}")
[[ -z "${SKILLS[0]:-}" ]] && SKILLS=(paper-session scan-back)

# unzip is needed too, for the file count and the font-license check below;
# python3 for the font-weight guard. Check all three up front: discovering one
# after the first bundle is rewritten leaves the tree half-built.
for tool in zip unzip python3; do
  command -v "$tool" >/dev/null || { echo "error: $tool not found" >&2; exit 1; }
done

check_fonts
# Runs on every build, whichever skill was named: the gate is about the pair, so
# checking only the skill being packaged would let `./build.sh scan-back` pass a
# tree whose other half no longer states the protocol. Like the font guard, it
# reads the source files and runs before anything is zipped.
check_couplings

for skill in "${SKILLS[@]}"; do
  if [[ ! -f "$skill/SKILL.md" ]]; then
    echo "error: $skill/SKILL.md not found — is '$skill' a skill directory?" >&2
    exit 1
  fi

  # SKILL.md must declare a name matching the directory, or the bundle installs
  # under one name and describes itself as another.
  declared=$(awk -F': *' '/^name:/ {gsub(/"/, "", $2); print $2; exit}' "$skill/SKILL.md")
  if [[ "$declared" != "$skill" ]]; then
    echo "error: $skill/SKILL.md declares name '$declared' but lives in '$skill/'" >&2
    exit 1
  fi

  find "$skill" -name '.DS_Store' -delete
  rm -f "$skill.skill"
  # -X drops extra file attributes (uid/gid, Finder metadata) for a cleaner,
  # more reproducible archive.
  zip -q -r -X "$skill.skill" "$skill" -x '*.DS_Store' '*__pycache__*' '*.pyc'

  files=$(unzip -Z1 "$skill.skill" | grep -vc '/$' || true)
  size=$(du -h "$skill.skill" | cut -f1)
  echo "built $skill.skill — $files files, $size"
done

# The fonts' license must travel with the fonts (SIL OFL 1.1). Fail loudly if a
# build would ship them without it.
if [[ -f paper-session.skill ]]; then
  # Capture first: `... | grep -q` exits early, and under `pipefail` the SIGPIPE
  # on unzip would make this check fail even when the file is present.
  listing=$(unzip -Z1 paper-session.skill)
  if [[ "$listing" != *"assets/fonts/LICENSE-IBMPlex.txt"* ]]; then
    echo "error: paper-session.skill ships fonts without LICENSE-IBMPlex.txt" >&2
    exit 1
  fi
fi

# All three paste sources live under paper-session/, so any run that touches
# that skill regenerates the artifact. `./build.sh paper-session` alone would
# otherwise refresh the bundle and leave the paste stale on disk, to be found
# only in CI; `./build.sh scan-back` alone cannot stale it and does not rewrite it.
for skill in "${SKILLS[@]}"; do
  if [[ "$skill" == paper-session ]]; then
    write_paste
    break
  fi
done

echo "ok"
